### ISSUE TITLE
Error in log from Home Assistant

### ISSUE THREAD

**Issue by coolbox13** [zachowj/hass-node-red#122]
## Version of the custom_component
v1.0.6
-->

## Configuration

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

## Describe the bug
 I do get a lot of ERROR's in the HOAS log file. My sensors out from node red are working properly

## Debug log

```text

2022-02-24 14:28:51 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

```

**Comment by zachowj** [comment]
Pretty sure this error is not caused by this repo.
