### ISSUE TITLE
Error doing job: Fatal error on SSL transport

### ISSUE THREAD

**Issue by mathias-ewald** [zachowj/hass-node-red#147]
## Versions
hass-node-red custom component: 1.0.9
home assistant: core-2022.5.4

## Describe the bug
After copying the files from `custom_components/nodered` into `custom_components/nodered` of my instance of Home Assistant, when I reboot Home Assistant the error `Error doing job: Fatal error on SSL transport` shows.

## Debug log

```text
2022-09-17 10:44:32 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Fatal error on SSL transport
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 924, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 719, in _fatal_error
    self._force_close(exc)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 731, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2022-09-17 10:50:46 ERROR (MainThread) [homeassistant] Error doing job: Fatal error on SSL transport
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 924, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 719, in _fatal_error
    self._force_close(exc)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 731, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[finish] process exit code 100
2022-09-17 10:50:47 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by mathias-ewald** [comment]
Works on 2022.9.4
