### ISSUE TITLE
Node-RED Companion // Deprecated API warning - Node-RED 4.0

### ISSUE THREAD

**Issue by hklages** [zachowj/hass-node-red#211]
## Configuration

Home Assistant is on unraid in a virtual machine (linux, qcow) and Node-RED on unraid as a Docker (standard installation). 
Do you need additional information?

## Describe the issue - EARLY WARNING!

When using the "event" or "current state" node I receive the message: 

Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.

## Debug log

Node-RED debug window: 

```text

Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.

 at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at TypedInputService.getValue (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
    at EventsAll.getTypedInputValue (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:134:39)
    at /data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:138:32
    at Array.forEach (<anonymous>)
    at EventsAll.setCustomOutputs (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:137:20)
    at EventsAll.onHaEventsAll (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/events-all/controller.js:57:18)
    at EventEmitter.<anonymous> (/data/node_modules/node-red-contrib-home-assi...

```

Could not find any relevant information in the attached log

```text

2023-09-26 08:49:32.717 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.719 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.722 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.724 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration grocy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.726 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration rademacher which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.728 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:32.730 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-26 08:49:48.222 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-09-26 08:50:18.615 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.178.15' for synology_dsm integration not ready yet: ClientConnectorError = ConnectionKey(host='192.168.178.15', port=5000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=3117482948372352207); Retrying in background
2023-09-26 08:50:22.339 WARNING (MainThread) [homeassistant.config_entries] Config entry 'googleTV' for androidtv_remote integration not ready yet: Couldn't connect to 192.168.178.58:6466; Retrying in background
2023-09-26 08:50:27.478 ERROR (MainThread) [homeassistant.components.binary_sensor] rpi_power: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/rpi_power/binary_sensor.py", line 52, in update
    value = self._under_voltage.get()
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-09-26 08:50:28.604 ERROR (MainThread) [tibber.home] Error in rt_subscribe
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tibber/home.py", line 439, in _start
    async for data in self._tibber_control.realtime.sub_manager.session.subscribe(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'session'
2023-09-26 08:50:42.595 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.last_meter_consumption_schubertstr_4') | round | int}}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1647, in forgiving_round
    value = round(float(value), precision)
                  ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1652, in forgiving_round
    raise_no_default("round", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1628, in raise_no_default
    raise ValueError(
ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.last_meter_consumption_schubertstr_4') | round | int}}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.last_meter_consumption_schubertstr_4') | round | int}}' but no default was specified
2023-09-26 08:50:42.615 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: round got invalid input 'unavailable' when rendering template '{{ states('sensor.last_meter_consumption_schubertstr_4') | round | int}}' but no default was specified') while processing template 'Template<template=({{ states('sensor.last_meter_consumption_schubertstr_4') | round | int}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.flat_current_meter'
2023-09-26 08:50:42.693 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states | rejectattr('domain', '!=', 'update') | rejectattr('state','==', 'off') | rejectattr('state','==', 'unavailable') | rejectattr('state','==', 'unknown') | list | count | int
 + states('sensor.hacs') | int 
}}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1946, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1628, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states | rejectattr('domain', '!=', 'update') | rejectattr('state','==', 'off') | rejectattr('state','==', 'unavailable') | rejectattr('state','==', 'unknown') | list | count | int
 + states('sensor.hacs') | int 
}}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states | rejectattr('domain', '!=', 'update') | rejectattr('state','==', 'off') | rejectattr('state','==', 'unavailable') | rejectattr('state','==', 'unknown') | list | count | int
 + states('sensor.hacs') | int 
}}' but no default was specified
2023-09-26 08:50:42.712 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states | rejectattr('domain', '!=', 'update') | rejectattr('state','==', 'off') | rejectattr('state','==', 'unavailable') | rejectattr('state','==', 'unknown') | list | count | int
 + states('sensor.hacs') | int 
}}' but no default was specified') while processing template 'Template<template=({{ states | rejectattr('domain', '!=', 'update') | rejectattr('state','==', 'off') | rejectattr('state','==', 'unavailable') | rejectattr('state','==', 'unknown') | list | count | int
 + states('sensor.hacs') | int 
}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.shs_number_of_updates_available'
2023-09-26 08:50:47.791 ERROR (MainThread) [zigpy.device] Failed to parse message (b'81840286') on cluster 32799, because Data is too short to contain 1 bytes
2023-09-26 08:50:47.864 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.grocy_chores exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-26 08:50:47.886 ERROR (MainThread) [zigpy.device] Failed to parse message (b'81840286') on cluster 32799, because Data is too short to contain 1 bytes
2023-09-26 08:50:48.222 WARNING (MainThread) [homeassistant.components.frontend] Theme hkTheme not found
2023-09-26 08:51:05.401 ERROR (MainThread) [custom_components.rademacher] Timeout fetching rademacher data
2023-09-26 08:51:29.919 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.grocy_chores exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
2023-09-26 08:51:32.473 ERROR (MainThread) [tibber.realtime] Watchdog: Connection is down, 2023-09-26 08:51:42.473630
2023-09-26 08:51:32.984 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.last_meter_production_schubertstr_4 has state class total_increasing, but its state is negative. Triggered by state -1 with last_updated set to 2023-09-26T06:44:59.999999+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
2023-09-26 08:55:10.331 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.grocy_chores (Chore(s)) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-09-26 09:03:10.444 WARNING (Recorder) [homeassistant.components.recorder.entity_registry] Cannot migrate history for entity_id `sensor.tz3000_dfgbtub0_ts0042_battery` to `sensor.switch_kitchen_battery` because the new entity_id is already in use
2023-09-26 09:10:29.517 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:14:55.299 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:14:58.220 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_title' is undefined when rendering '{{ notification_title}}'
2023-09-26 09:14:58.224 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_message' is undefined when rendering '{{ notification_message }}'
2023-09-26 09:15:47.698 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:16:53.615 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_title' is undefined when rendering '{{ notification_title}}'
2023-09-26 09:16:53.618 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_message' is undefined when rendering '{{ notification_message }}'
2023-09-26 09:17:16.647 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_title' is undefined when rendering '{{ notification_title}}'
2023-09-26 09:17:16.652 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_message' is undefined when rendering '{{ notification_message }}'
2023-09-26 09:18:16.998 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:18:34.729 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:19:00.760 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_title' is undefined when rendering '{{ notification_title}}'
2023-09-26 09:19:00.764 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'notification_message' is undefined when rendering '{{ notification_message }}'
2023-09-26 09:25:21.096 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running
2023-09-26 09:26:38.673 WARNING (MainThread) [custom_components.localtuya.common] [bf8...zaw] Disconnected - waiting for discovery broadcast
2023-09-26 09:27:27.182 WARNING (MainThread) [homeassistant.components.script.notification_to_smartphone] Notification To Smartphone : Already running


```

**Comment by zachowj** [comment]
Duplicate https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/898
