### ISSUE TITLE
Not loading with HA 2024.10.0b0

### ISSUE THREAD

**Issue by andreasbrett** [zachowj/hass-node-red#301]
### Describe the bug

The integration crashes on load with the following error:

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 21:40:41 (1 occurrences)
Last logged: 21:40:41

Setup failed for custom integration 'nodered': Unable to import component: cannot import name 'async_get_default_agent' from 'homeassistant.components.conversation.default_agent' (/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nodered/__init__.py", line 59, in <module>
    from .websocket import register_websocket_handlers
  File "/config/custom_components/nodered/websocket.py", line 47, in <module>
    from custom_components.nodered.sentence import (
  File "/config/custom_components/nodered/sentence.py", line 7, in <module>
    from homeassistant.components.conversation.default_agent import (
ImportError: cannot import name 'async_get_default_agent' from 'homeassistant.components.conversation.default_agent' (/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/nodered/__init__.py", line 59, in <module>
    from .websocket import register_websocket_handlers
  File "/config/custom_components/nodered/websocket.py", line 47, in <module>
    from custom_components.nodered.sentence import (
  File "/config/custom_components/nodered/sentence.py", line 7, in <module>
    from homeassistant.components.conversation.default_agent import (
ImportError: cannot import name 'async_get_default_agent' from 'homeassistant.components.conversation.default_agent' (/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py)
```

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.10.0b0
Companion version: 0.0.0

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v20.15.1 arm64 linux
OS: Linux 5.10.60-rockchip64 arm64

**Comment by andreasbrett** [comment]
This commit seems to be the cause:
https://github.com/home-assistant/core/pull/126332

**Comment by cloudbr34k84** [comment]
adding a +1 to this issue
